#include "arduino_secrets.h"
// MQ135 - Version: Latest 


/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/9ef6f1ec-5a4c-493d-b9ef-270afe88f9d5

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight lED;
  CloudTemperatureSensor temperature;
  CloudRelativeHumidity humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "DHT.h"
#include "MQ135.h"

#define SENSOR 4
#define DHTPIN 15
#define DHTTYPE DHT11


DHT dht(DHTPIN, DHTTYPE);




void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  pinMode(LED_BUILTIN, OUTPUT);


  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(100);

  dht.begin();


  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  SENSOR_READ();
  delay(1500);
  // Your code here
  

}
void onLEDChange()  {
  if (lED == 1) {
    digitalWrite(LED_BUILTIN, HIGH);
    Serial.print("LED ON");
  }
  if (lED == 0) {
    digitalWrite(LED_BUILTIN, LOW);
    Serial.print("LED OFF");
  }

  // Add your code here to act upon LED change
}


void SENSOR_READ()
{
  float hum = dht.readHumidity();
  float temp = dht.readTemperature();
 // MQ135 gasSensor = MQ135(SENSOR);
  //float air_quality = mq135_sensor.getPPM();
  float air = random(5000, 5200);
  pPM = air;
  temperature = temp;
  humidity = hum;
 // air = air_quality;
  
  Serial.print("Humidity: ");
  Serial.print(hum);
  Serial.print(" %, Temp: ");
  Serial.print(temp);
  Serial.println(" Celsius");
  Serial.println(air);
  Serial.println("PPM");
  
}
